config/routes.rb
Rails.application.routes.draw do
  get 'city/show'
  resources :gossip do
  	resources :comment
  end
  
  resources :author
  resources :welcome, only: [:index, :show]
  resources :contact, only: [:index]
  resources :team, only: [:index]
  resources :city, except: [:destroy] 
  root 'welcome#index'
  
  resources :sign_up, only: [:new]
  resources :users, only: [:create] 
  #resources :log_in 
  resources :log_in, only: [:new]
  resources :log_out, only: [:destroy] 
  #post '/log_in', to: 'log_in#new', as:'log_in'
  #get ‘/signup’ => ‘users#new’
  #post ‘/users’ => ‘users#create

  #“new” will be for your signup page view, 
  #and the“create” action will store the user’s information in your database.
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
	validates :content, presence: true
	validates :user_id, presence: true
	validates :gossip_id, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :join_gossip_tags
	has_many :tags, through: :join_gossip_tags
	has_many :comments
	validates :title, presence: true
	validates :content, presence: true
	validates :user_id, presence: true
end

app/models/join_gossip_tag.rb
class JoinGossipTag < ApplicationRecord
	belongs_to :tag
	belongs_to :gossip

end

app/models/join_pm_recipient.rb
class JoinPmRecipient < ApplicationRecord
	belongs_to :private_message
	belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :user
	has_many :join_pm_recipients
	validates :content, presence: true
	validates :user_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_gossip_tags
	has_many :gossips, through: :join_gossip_tags
	has_many :users, through: :gossips
	validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	belongs_to :city
	has_many :gossips
	has_many :comments
	has_many :tags, through: :gossips
	has_many :private_messages
  	has_many :join_pm_recipients
  	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  	validates :first_name, presence: true
  	validates :last_name, presence: true
  	#validates :name, presence: true
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/log_in_helper.rb
module LogInHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>TGP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
<nav class="navbar navbar-expand-lg navbar-light text-light bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand text-white" <%= link_to "The Gossip Project", welcome_index_path%></a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link text-light" <%= link_to "Team", team_index_path%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-light" <%= link_to "Contact", contact_index_path%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-light" <%= link_to "Sign up", new_sign_up_path%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-light" <%= link_to "Log in", new_log_in_path%></a>
      </li>

    </ul>
  </div>
</nav>
  </header>
  <body>
    
    <%= yield %>
  </body>
</html>